language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging

  - docker build . -f udagram-api-feed/Dockerfile
  - docker tag udagram-api-feed:latest mbuvi/udagram-api-feed:v1

  - docker build . -f udagram-api-user/Dockerfile
  - docker tag udagram-api-user:latest mbuvi/udagram-api-user:v1

  - docker build . -f udagram-frontend/Dockerfile
  - docker tag udagram-frontend:local mbuvi/udagram-frontend:v1

  - docker build . -f udagram-reverseproxy/Dockerfile
  - docker tag reverseproxy:latest mbuvi/reverseproxy:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push mbuvi/udagram-api-feed:v1
  - docker push mbuvi/udagram-api-user:v1
  - docker push mbuvi/udagram-frontend:v1
  - docker push mbuvi/reverseproxy:v1

