language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  docker build . -t mbuvi/udagram-api-feed:v1 -f udagram-api-feed/Dockerfile
  docker build . -t mbuvi/udagram-api-user:v1 -f udagram-api-user/Dockerfile
  docker build . -t mbuvi/udagram-frontend:v1 -f udagram-frontend/Dockerfile
  docker build . -t mbuvi/reverseproxy:v1 -f udagram-reverseproxy/Dockerfile

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push mbuvi/udagram-api-feed:v1
  - docker push mbuvi/udagram-api-user:v1
  - docker push mbuvi/udagram-frontend:v1
  - docker push mbuvi/reverseproxy:v1

